[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flake8_innerscope"
version = "0.1.0"
description = "A flake8 plugin to enforce strict local scope usage with @innerscope decorator"
authors = [
  { name = "hprodh" }
]
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Framework :: Flake8",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"
dependencies = [
    "flake8 >= 3.0.0",
]

[project.entry-points."flake8.extension"]
INN = "flake8_innerscope.innerscope:InnerScopeChecker"
